apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-scan-email
  name: web-scan-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-scan-email
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-scan-email
    spec:
      containers:
      - image: web-scan-email
        name: web-scan-email
        resources: {}
status: {}
