apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  labels:
    app: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
      - name: maildev
        image: maildev/maildev:2.1.0
        ports:
        - containerPort: 1080
          name: web
        - containerPort: 1025
          name: smtp
        resources:
          limits:
            memory: 512Mi
            cpu: 100m
          requests:
            memory: 256Mi
            cpu: 50m
        
---
apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  selector:
    app: maildev
  ports:
  - name: web
    port: 1080
    targetPort: 1080
  - name: smtp
    port: 1025
    targetPort: 1025
  type: ClusterIP