resources:
  - deployment-frontend.yaml
  - deployment-crawler.yaml
  - deployment-maildev.yaml
  - svc-dev-frontend.yaml
  - svc-crawler.yaml
  - ingress-dev-frontend.yaml
  - ingress-crawler.yaml
  - ingress-maildev.yaml
