resources:
  - web-scan-frontend.yaml
  - web-scan-crawler.yaml
  - web-scan-svc-dev.yaml
  - web-scan-crawler-svc.yaml
  - frontend-ingress-dev.yaml
  - crawler-ingress.yaml
  - ingress-maildev.yaml
  - deployment-maildev.yaml