apiVersion: v1
kind: Service
metadata:
  namespace:  {{ .Values.namespace }}
  labels:
    app: keycloak
  name: keycloak-discovery
spec:
  selector:
    app: keycloak
  clusterIP: None
  type: ClusterIP