apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "webscanner.frontendName" . }}
  labels:
    app: {{ include "webscanner.frontendName" . }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "webscanner.frontendName" . }}
  template:
    metadata:
      labels:
        app: {{ include "webscanner.frontendName" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{.Values.frontend.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10

