apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  creationTimestamp: null
  labels:
    app: {{ include "webscanner.emailName" . }}
  name: {{ include "webscanner.emailName" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "webscanner.emailName" . }}
  template:
    metadata:
      labels:
        app: {{ include "webscanner.emailName" . }}
    spec:
      containers:
      - image: {{ .Values.email.image }}:{{ .Values.email.tag }}
        name: {{ include "webscanner.emailName" . }}
        env:
        - name: EMAIL
          value: {{ .Values.email.env.email }}
        - name: PASSWORD 
          value: {{ .Values.email.env.password }}
        - name: HOST
          value: {{ .Values.email.env.host }}
        - name: HOSTPORT
          value: {{ .Values.email.env.hostPort | quote }}
        readinessProbe:
          httpGet:
            path: /healz
            port: {{ .Values.email.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healz
            port: {{ .Values.email.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
