---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-watcher
  namespace: web-scanner-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
  namespace: web-scanner-dev
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-binding
  namespace: web-scanner-dev
subjects:
- kind: ServiceAccount
  name: job-watcher
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
