apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: maildev-ingress
spec:
  rules:
  - host: maildev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maildev
            port:
              number: 1080