apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "webscanner.frontendName" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ include "webscanner.frontendName" . }}
