apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  creationTimestamp: null
  labels:
    app: {{ include "webscanner.crawlerName" . }}
  name: {{ include "webscanner.crawlerName" . }}
spec:
  replicas: {{ .Values.crawler.replicas }}
  selector:
    matchLabels:
      app: {{ include "webscanner.crawlerName" . }}
  template:
    metadata:
      labels:
        app: {{ include "webscanner.crawlerName" . }}
    spec:
      containers:
      - image: {{ .Values.crawler.image.name }}:{{.Values.crawler.image.tag}}
        name: {{ include "webscanner.crawlerName" . }}
        imagePullPolicy: {{ .Values.crawler.image.imagePullPolicy }}
        resources: {}
        env:
        - name: MAXCRAWL
          value: {{ .Values.crawler.env.maxCrawl | quote}}
        - name: PORT
          value: {{ .Values.crawler.service.targetPort | quote }}
        - name: GOOGLE_CSE_ID
          value: {{ .Values.crawler.env.GOOGLE_CSE_ID }}
        - name: GOOGLE_API_KEY
          value: {{ .Values.crawler.service.GOOGLE_API_KEY }}
        readinessProbe:
          httpGet:
            path: /healz
            port: {{ .Values.crawler.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healz
            port: {{ .Values.crawler.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
