apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: crawler-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /crawler(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "webscanner.crawlerName" . }}
            port:
              number: {{ .Values.crawler.service.port }}
