apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "webscanner.crawlerName" . }}
  name: {{ include "webscanner.crawlerName" . }}
spec:
  ports:
  - port: {{ .Values.crawler.service.port }}
    protocol: TCP
    targetPort: {{ .Values.crawler.service.targetPort }}
  type: ClusterIP
  selector:
    app: {{ include "webscanner.crawlerName" . }}
status:
  loadBalancer: {}
