apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ include "webscanner.analyzerName" . }}
  name: {{ include "webscanner.analyzerName" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.analyzer.port }}
    protocol: TCP
    targetPort: {{ .Values.analyzer.targetPort }}
  selector:
    app: {{ include "webscanner.analyzerName" . }}
  type: ClusterIP
status:
  loadBalancer: {}
