apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.postgres.deployment.name }}
  labels:
    app: {{ .Values.postgres.deployment.name }}
spec:
  replicas: {{ .Values.postgres.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.deployment.name }}
          image: mirror.gcr.io/postgres:17
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.deployment.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.deployment.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.deployment.db }}
            - name: POSTGRES_LOG_STATEMENT
              value: {{ .Values.postgres.deployment.logstatement }}
          ports:
            - name: {{ .Values.postgres.deployment.name }}
              containerPort: {{ .Values.postgres.deployment.targetPort }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: keycloak-storage
